repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix', 'lf']
  - repo: local
    hooks:
      - id: gradle-check
        name: Gradle checkstyle and test
        entry: ./gradlew checkstyleMain checkstyleTest clean test
        language: system
        pass_filenames: false
