apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cronjob-log-monitor
build:
  artifacts:
    - image: ghcr.io/octopilot/cronjob-log-monitor
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: cronjob-log-monitor
        chartPath: chart
        setValueTemplates:
          # Artifact name with / . - replaced by _ for template env
          image: "{{.IMAGE_FULLY_QUALIFIED_ghcr_io_octopilot_cronjob_log_monitor}}"
