apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: cronjob-log-monitor
build:
  artifacts:
    - image: ghcr.io/octopilot/cronjob-log-monitor
      context: .
      buildpacks:
        builder: ghcr.io/octopilot/builder-jammy-base:rust-builder-d84dd54
    - image: ghcr.io/octopilot/cronjob-log-monitor-chart
      context: chart
      buildpacks:
        builder: ghcr.io/octopilot/builder-jammy-base:rust-builder-d84dd54
    - image: ghcr.io/octopilot/cronjob-log-monitor-integration-cronjob
      context: tests/integration/cronjob-app
      buildpacks:
        builder: paketobuildpacks/builder-jammy-base
        env:
          - BP_JVM_VERSION=21
